---

- name: install software properties common
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - software-properties-common
  always_run: yes

- name: Add Oracle Java Repository
  apt_repository:
    repo: 'ppa:webupd8team/java'
  always_run: yes

- name: Accept Java 8 Licence
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
  args:
    creates: /etc/oracle-java-8-licence-acceptance
  always_run: yes

- name: apt-update
  apt: update_cache=yes
  always_run: yes

- name: Install Oracle Java 8
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default