---

- name: percona | add percona apt key
  apt_key: url=http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona state=present


- name: percona | add percona repo
  apt_repository: repo="deb http://repo.percona.com/apt {{ ansible_distribution_release }} main" state=present


- name: percona | install percona
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=900
  with_items:
  - percona-server-server-5.6
  - percona-server-client-5.6
  - percona-toolkit