---

- name: Add repository for python3
  apt_repository:
    repo: 'ppa:fkrull/deadsnakes'


- name: update apt cache
  apt: update_cache=yes


- name: Install Python3
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - python3
  - python3-setuptools
  - python3-dev
  - libmysqlclient-dev
  - python-tk


- name: Install pip
  easy_install:
    executable: easy_install3
    name: pip
    state: latest


- name: Install data science modules
  pip:
    executable: pip3
    name: "{{ item }}"
    state: present
  with_items:
  - setuptools==3.3
  - ipython==4.2.0
  - numpy==1.11.0
  - scipy==0.17.1
  - scikit-learn==0.17.1
  - virtualenv==15.0.1
  - virtualenvwrapper==4.7.1
  - Flask==0.10.1
  - Flask-RESTful==0.3.5
  - gunicorn==19.6.0
  - requests==2.10.0
  - pandas==0.18.1
  - nose==1.3.7
  - matplotlib==1.5.1
  - mysqlclient==1.3.7
  - pillow==3.2.0
  - spacy


- name: Install statsmodels
  easy_install:
    executable: /usr/bin/easy_install3
    name: statsmodels
    state: latest

#
#- name: Make python3 the default (remove link to 2.7)
#  file:
#    path: '/usr/bin/python'
#    state: absent
#
#
#- name: Make python3 default (add link to 3)
#  file:
#    src: '/usr/bin/python3'
#    dest: '/usr/bin/python'
#    owner: root
#    group: root
#    state: link
